name: Preview SPA on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  push:
    branches:
      - feature/gis-secure-retry
    paths:
      - 'ar-dashboard-spa/**'
      - '.github/workflows/pages-preview.yml'

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: 'pages-preview'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        working-directory: ar-dashboard-spa
        run: npm install --no-audit --no-fund
      - name: Build
        working-directory: ar-dashboard-spa
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ar-dashboard-spa/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Preview to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
      - name: Comment preview URL on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Preview is ready: ${{ steps.deployment.outputs.page_url }}
